[versions]
agp = "8.2.0-alpha13"
androidxActivity = "1.8.0-alpha06"
bouncycastle = "1.75"
moshi = "1.15.0"
# @keep used for kotlinCompilerExtensionVersion
composeCompiler = "1.5.0-dev-k1.9.0-6a60475e07f"
coroutines = "1.7.2"
flowbinding = "1.2.0"
hilt = "2.47"
kotlin = "1.9.0"
kotlin1710 = { strictly = "[1.7.0,)", prefer = "1.7.10" }
leakcanary = "2.12"
lifecycle = "2.6.1"

[libraries]
android-desugarJdkLibs = "com.android.tools:desugar_jdk_libs:2.0.3"
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidx-annotation = "androidx.annotation:annotation:1.7.0-alpha02"
androidx-appcompat = "androidx.appcompat:appcompat:1.7.0-alpha02"
androidx-autofill = "androidx.autofill:autofill:1.3.0-alpha01"
androidx-biometricKtx = "androidx.biometric:biometric-ktx:1.2.0-alpha05"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.2.0-alpha10"
androidx-core-ktx = "androidx.core:core-ktx:1.10.1"
androidx-documentfile = "androidx.documentfile:documentfile:1.1.0-alpha01"
androidx-fragment-ktx = "androidx.fragment:fragment-ktx:1.7.0-alpha01"
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycle" }
androidx-lifecycle-livedataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-material = "com.google.android.material:material:1.9.0"
androidx-preference = "androidx.preference:preference:1.2.0"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.3.1-rc01"
androidx-recyclerviewSelection = "androidx.recyclerview:recyclerview-selection:1.2.0-alpha01"
androidx-security = "androidx.security:security-crypto-ktx:1.1.0-alpha06"
androidx-swiperefreshlayout = "androidx.swiperefreshlayout:swiperefreshlayout:1.2.0-alpha01"
aps-sublimeFuzzy = "com.github.android-password-store:sublime-fuzzy:2.3.4"
aps-zxingAndroidEmbedded = "com.github.android-password-store:zxing-android-embedded:4.2.1"
build-agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
build-diffutils = "io.github.java-diff-utils:java-diff-utils:4.12"
build-download = "de.undercouch:gradle-download-task:5.4.0"
build-javapoet = "com.squareup:javapoet:1.13.0"
build-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
build-ktfmt = "com.facebook:ktfmt:0.44"
build-mavenpublish = "com.vanniktech:gradle-maven-publish-plugin:0.25.3"
build-metalava = "me.tylerbwong.gradle.metalava:plugin:0.3.3"
build-moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
build-moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
build-okhttp = "com.squareup.okhttp3:okhttp:4.11.0"
build-r8 = "com.android.tools:r8:8.2.7-dev"
build-semver = "com.vdurmont:semver4j:3.1.0"
build-sentry = "io.sentry.android.gradle:io.sentry.android.gradle.gradle.plugin:3.11.1"
build-vcu = "nl.littlerobots.version-catalog-update:nl.littlerobots.version-catalog-update.gradle.plugin:0.8.1"
build-versions = "com.github.ben-manes:gradle-versions-plugin:0.47.0"
compose-animation = { module = "androidx.compose.animation:animation" }
compose-bom = "androidx.compose:compose-bom:2023.06.01"
compose-foundation-core = { module = "androidx.compose.foundation:foundation" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-hilt = "androidx.hilt:hilt-navigation-compose:1.0.0"
compose-material = { module = "androidx.compose.material:material" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-ui-core = { module = "androidx.compose.ui:ui" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
dagger-hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin1710-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin1710" }
kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
testing-junit = "junit:junit:4.13.2"
testing-kotlintest-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
testing-robolectric = "org.robolectric:robolectric:4.10.3"
testing-sharedPrefsMock = "com.github.android-password-store:shared-preferences-fake:2.0.0"
testing-testparameterinjector = "com.google.testparameterinjector:test-parameter-injector:1.12"
testing-turbine = "app.cash.turbine:turbine:1.0.0"
thirdparty-bouncycastle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk15to18", version.ref = "bouncycastle" }
thirdparty-bouncycastle-bcprov = { module = "org.bouncycastle:bcprov-jdk15to18", version.ref = "bouncycastle" }
thirdparty-commons_codec = "commons-codec:commons-codec:1.14"
thirdparty-compose-lints = "com.slack.lint.compose:compose-lint-checks:1.2.0"
thirdparty-eddsa = "net.i2p.crypto:eddsa:0.3.0"
thirdparty-fastscroll = "me.zhanghai.android.fastscroll:library:1.2.0"
thirdparty-flowbinding-android = { module = "io.github.reactivecircus.flowbinding:flowbinding-android", version.ref = "flowbinding" }
# JGit upgrades also raise its minimum Java runtime requirements that we cannot satisfy on Android
# noinspection GradleDependency
thirdparty-jgit = "org.eclipse.jgit:org.eclipse.jgit:3.7.1.201504261725-r"
thirdparty-kotlinResult = "com.michael-bull.kotlin-result:kotlin-result:1.1.18"
thirdparty-leakcanary-core = { module = "com.squareup.leakcanary:leakcanary-android-core", version.ref = "leakcanary" }
thirdparty-logcat = "com.squareup.logcat:logcat:0.1"
thirdparty-modernAndroidPrefs = "de.maxr1998:modernandroidpreferences:2.3.2"
thirdparty-nonfree-googlePlayAuthApiPhone = "com.google.android.gms:play-services-auth-api-phone:18.0.1"
thirdparty-nonfree-sentry = "io.sentry:sentry-android:6.26.0"
thirdparty-pgpainless = "org.pgpainless:pgpainless-core:1.6.0"
thirdparty-plumber = { module = "com.squareup.leakcanary:plumber-android-startup", version.ref = "leakcanary" }
thirdparty-slack-lints = "com.slack.lint:slack-lint-checks:0.4.0"
# TODO: Remove the explicit bcpkix dependency when upgrading this to a BC 1.71 compatible version
thirdparty-sshj = "com.hierynomus:sshj:0.35.0"
thirdparty-uri = "com.eygraber:uri-kmp:0.0.13"
thirdparty-whatthestack = "com.github.haroldadmin:WhatTheStack:1.0.0-alpha04"

[bundles]
androidxLifecycle = [
    "androidx-lifecycle-common",
    "androidx-lifecycle-livedataKtx",
    "androidx-lifecycle-viewmodelKtx",
]
testDependencies = [
    "testing-junit",
    "testing-kotlintest-junit",
]

[plugins]
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
