name: Publish APS binaries to GitHub Releases
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build release binaries
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Accept all SDK licenses
      shell: bash
      run: printf 'y\ny\ny\ny\ny\ny\n' | $ANDROID_HOME/tools/bin/sdkmanager --licenses

    - name: Get build-tools directory
      id: build-tools-path
      shell: bash
      run: echo "dir=${ANDROID_HOME}/build-tools/34.0.0" >> "${GITHUB_OUTPUT}"

    - name: Cache build-tools
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
      with:
        path: ${{ steps.build-tools-path.outputs.dir }}
        key: ${{ runner.os }}-34.0.0

    - name: Set up JDK
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        distribution: temurin
        java-version: 18

    - name: Decrypt secrets
      run: scripts/signing-setup.sh "$ENCRYPT_KEY"
      env:
        ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Build release binaries
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: :app:assembleFreeRelease :app:assembleNonFreeRelease :app:bundleNonFreeRelease
        gradle-home-cache-cleanup: true
      env:
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

    - name: Upload non-free release APK
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: APS Non-Free Release APK
        path: app/build/outputs/apk/nonFree/release/app-nonFree-release.apk

    - name: Upload non-free release Bundle
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: APS Non-Free Release Bundle
        path: app/build/outputs/bundle/nonFreeRelease/app-nonFree-release.aab

    - name: Upload free release APK
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: APS Free Release APK
        path: app/build/outputs/apk/free/release/app-free-release.apk

    - name: Clean secrets
      if: "${{ always() }}"
      run: scripts/signing-cleanup.sh

  create_github_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Get Non-Free Release APK
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: APS Non-Free Release APK
          path: artifacts/nonFree

      - name: Get Non-Free Bundle
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: APS Non-Free Release Bundle
          path: artifacts/nonFree

      - name: Get Free Release APK
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: APS Free Release APK
          path: artifacts/free

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@b97ce03a10d9bdbb07beb491c76a5a01d78cd3ef # v2.2.2
        with:
          version: ${{ github.ref }}
          path: ./CHANGELOG.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: true
          prerelease: false

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Upload Non-Free Release Apk
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/nonFree/app-nonFree-release.apk
          asset_name: APS-nonFree_${{ steps.get_version.outputs.VERSION }}.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Non-Free Release Bundle
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/nonFree/app-nonFree-release.aab
          asset_name: APS-nonFree_${{ steps.get_version.outputs.VERSION }}.aab
          asset_content_type: application/octet-stream

      - name: Upload Free Release Apk
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/free/app-free-release.apk
          asset_name: APS-free_${{ steps.get_version.outputs.VERSION }}.apk
          asset_content_type: application/vnd.android.package-archive
