name: "Release library subprojects"
on:
  push:
    tags:
      - openpgp-ktx-v*
      - autofill-parser-v*

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.0

    - name: Set up JDK
      uses : actions/setup-java@v2.4.0
      with :
        distribution : 'zulu'
        java-version : '17'
        cache: 'gradle'

    - name: Determine publishing task
      id: task-select
      run: |
        set -x
        TAG=${GITHUB_REF/refs\/tags\//}
        if [[ "${TAG}" =~ "openpgp-ktx" ]]; then
          echo '::set-output name=PROJECT::openpgp-ktx'
        elif [[ "${TAG}" =~ "autofill-parser" ]]; then
          echo '::set-output name=PROJECT::autofill-parser'
        fi

    - name: Upload binaries
      uses: gradle/gradle-build-action@v2.1.2
      with:
        arguments: :${{ steps.task-select.outputs.PROJECT }}:publishAllPublicationsToMavenCentralRepository
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.NEXUS_PUBLISH_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.NEXUS_PUBLISH_PASSWORD }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.NEXUS_PUBLISH_GPG_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.NEXUS_PUBLISH_GPG_KEY_PASSWORD }}

    - name: Close and release repository
      uses: gradle/gradle-build-action@v2.1.2
      with:
        arguments: closeAndReleaseRepository
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.NEXUS_PUBLISH_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.NEXUS_PUBLISH_PASSWORD }}
