name: Release library subprojects
on:
  push:
    tags:
      - autofill-parser-v*

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
    - name: Setup build environment
      uses: android-password-store/android-password-store/.github/reusable-workflows/setup-gradle@develop

    - name: Upload binaries
      shell: bash
      run: ./gradlew --no-configuration-cache :autofill-parser:publishAllPublicationsToMavenCentralRepository
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.NEXUS_PUBLISH_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.NEXUS_PUBLISH_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.NEXUS_PUBLISH_GPG_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.NEXUS_PUBLISH_GPG_KEY_PASSWORD }}
