name: Release library subprojects
on:
  push:
    tags:
      - autofill-parser-v*

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.0.2

    - name: Set up JDK
      uses: actions/setup-java@v3.4.1
      with:
        distribution: temurin
        java-version: 17

    - name: Upload binaries
      uses: gradle/gradle-build-action@v2.2.1
      with:
        arguments: --no-configuration-cache :autofill-parser:publishAllPublicationsToMavenCentralRepository
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.NEXUS_PUBLISH_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.NEXUS_PUBLISH_PASSWORD }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.NEXUS_PUBLISH_GPG_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.NEXUS_PUBLISH_GPG_KEY_PASSWORD }}

    - name: Close and release repository
      uses: gradle/gradle-build-action@v2.2.1
      with:
        arguments: --no-configuration-cache closeAndReleaseRepository
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.NEXUS_PUBLISH_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.NEXUS_PUBLISH_PASSWORD }}
